file_format: "1"
id: draculad
name: Draculad
type: shield
url: https://github.com/MangoIV/dracuLad
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
  - underglow
siblings:
  - draculad_left
  - draculad_right
